version: '3'
services:
    server:
        name: rent_wheels_server
        build: ./server
        ports:
            - 4000:4000
    client:
        container_name: rent_wheels_client
        build: ./client
        volumes:
            - './client:/app'
            - '/client/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING:'true'
